[package]
name = "exam_ide"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = { version = "0.6", features = ["csr"] }
leptos_router = { version = "0.6", features = ["csr"] }
console_error_panic_hook = "0.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.6"
web-sys = { version = "0.3", features = [
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "Storage",
    "Worker",
    "MessageEvent",
    "ErrorEvent",
    "Blob",
    "BlobPropertyBag",
    "Url",
    "Location",
] }
js-sys = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
gloo-utils = { version = "0.2", features = ["serde"] }
flate2 = "1.0"
base64 = "0.22"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
