[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"
filehash = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "cp _headers dist/_headers"]

[watch]
ignore = ["./dist", "./static/codemirror.bundle.js"]

[serve]
address = "127.0.0.1"
port = 8080
open = false
