[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npm install && npm run bundle-cm"]

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
ignore = ["./dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = false
